### ISSUE TITLE
Rename capacity_factors to capacity_factors_power

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.climate.stress.test#307]
Apparently capacity_factors (currently) only holds capacity_factors for the power sector ATM. This might be extended but I have no background knowledge on how likely and how soon that would happen, maybe @jacobvjk  knows more.
While the status quo is as it is I would suggest renaming read_capacity_factors to read_capacity_factors_power. If doing so please make sure it does not interfere with the webtool though/adjust webtool accordingly.

_Originally posted by @MirijaHa in https://github.com/2DegreesInvesting/r2dii.climate.stress.test/pull/302#discussion_r782783448_

**Comment by jacobvjk** [comment]
at this point, the power sector is the only sector that will require capacity factors. We get capacity on the asset/company level and need to translate that information to power generation by applying the capacity factor. This happens so that we can calculate the profits on units sold. For all other sectors that we currently cover, the asset level unit already holds the same type of information as is needed in the profit calculation.
